name: Run Tests and Analyze Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and run unit tests
        run: mvn clean test

      - name: Run Selenium tests
        run: mvn test -Pselenium

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.9
        with:
          organization: cesarherr
          projectKey: CesarHerr_Ev_devOps_Adalid
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
